'use client';
import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import Viewport,{type IfcMesh} from '../viewport';
type Footprint={type:string;coordinates:number[][][]};
type Result={meshes:IfcMesh[];footprints:Footprint[]};
const cases=[['baseline','Modelo original'],['different-thickness','Espessuras diferentes'],['different-height','Alturas diferentes']];
export default function Ensaios(){const [active,setActive]=useState('baseline'),[data,setData]=useState<Result|null>(null),[selected,setSelected]=useState('P01'),[error,setError]=useState(''),[reset,setReset]=useState(0);
useEffect(()=>{const abort=new AbortController();setData(null);setError('');fetch(`/ensaios/${active}.json`,{signal:abort.signal}).then(r=>{if(!r.ok)throw Error('Não foi possível carregar o cenário.');return r.json();}).then(value=>{const result=value as Result;if(!Array.isArray(result.meshes)||!Array.isArray(result.footprints)||result.meshes.length!==result.footprints.length)throw Error("Cenário inválido.");setData(result);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[active]);
const selectedMesh=data?.meshes.find(m=>m.id===selected);
return <main className="editor"><header className="titlebar"><strong><span className="brandmark">B</span> BRABIM</strong><span>Encontros de paredes · ensaios IFC</span><a href="/">Voltar ao editor</a></header><div className="viewbar"><Tabs value={active} onValueChange={v=>setActive(String(v))}><TabsList>{cases.map(([id,label])=><TabsTrigger key={id} value={id}>{label}</TabsTrigger>)}</TabsList></Tabs><button onClick={()=>setReset(v=>v+1)}>Enquadrar 3D</button></div><div className="workspace"><aside className="properties"><h2>Inspeção do resultado</h2><section style={{paddingTop:16}}><p>Geometria calculada pelo IfcOpenShell 0.8.5.</p><p className="hint">Cenários fixos, sem edição ou recálculo online. Selecione uma parede para identificá-la nas duas vistas.</p></section><section className="navigator"><h3>PAREDES</h3>{data?.meshes.map(m=><button className={m.id===selected?'selected':''} key={m.id} onClick={()=>setSelected(m.id)}>{m.id}<small>{m.height.toFixed(2)} m</small></button>)}</section>{selectedMesh&&<section><h3>ELEMENTO SELECIONADO</h3><p>{selectedMesh.id} · altura {selectedMesh.height.toFixed(2)} m</p><p className="hint" style={{overflowWrap:'anywhere'}}>IFC GUID: {selectedMesh.guid}</p></section>}<section><a href={`/ensaios/${active}.ifc`} download>Baixar IFC deste cenário</a><p className="hint">Os testes geométricos passaram nos três cenários. Revisão visual e técnica ainda necessária.</p></section></aside><div className="drawing">{error?<p role="alert">{error}</p>:!data?<p role="status">Carregando cenário…</p>:<div className="views split"><section className="view plan"><div className="view-title">Planta · projeção da malha IFC</div><svg className="plan-svg" viewBox="-5.4 -4 10.8 8" aria-label="Paredes calculadas pelo IfcOpenShell">{data.footprints.map((p,i)=><path key={data.meshes[i].id} d={p.coordinates.map(r=>'M'+r.map(v=>v.join(',')).join(' L')+' Z').join(' ')} fillRule="evenodd" fill={selected===data.meshes[i].id?'#258fc6':'#b8c5ce'} stroke="#374f60" strokeWidth=".02" role="button" tabIndex={0} aria-label={`Selecionar ${data.meshes[i].id}`} onClick={()=>setSelected(data.meshes[i].id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(data.meshes[i].id);}}}/> )}</svg><div className="view-caption">Linhas de encontro identificam limites entre elementos.</div></section><section className="view three"><div className="view-title">3D · malha gerada pelo motor IFC</div><Viewport walls={[]} meshes={data.meshes} selected={selected} onSelect={setSelected} reset={reset}/><div className="view-caption">Arraste para orbitar · roda para aproximar</div></section></div>}</div></div><footer>Ensaio de geometria · unidades em metros · sem validação para execução de obra</footer></main>;
}

