'use client';
import { useState } from 'react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { MousePointer2, Box, Layers, Undo2, RotateCcw, PanelLeft, Move } from 'lucide-react';
import Viewport from './viewport';
import {sitePath} from '@/lib/site-path';
import {useWallTool} from './use-wall-tool';
export type Wall = { id:string; name:string; x:number; z:number; length:number; angle:number; height:number; thickness:number };
const initial:Wall[] = [
{id:'P01',name:'Parede norte',x:0,z:-2.5,length:8,angle:0,height:2.8,thickness:.2},
{id:'P02',name:'Parede sul',x:0,z:2.5,length:8,angle:0,height:2.8,thickness:.2},
{id:'P03',name:'Parede oeste',x:-4,z:0,length:5,angle:Math.PI/2,height:2.8,thickness:.2},
{id:'P04',name:'Parede leste',x:4,z:0,length:5,angle:Math.PI/2,height:2.8,thickness:.2},
{id:'P05',name:'Divisória interna',x:1,z:0,length:5,angle:Math.PI/2,height:2.8,thickness:.15}];
export function LegacyHome(){
const [walls,setWalls]=useState(initial),[selected,setSelected]=useState('P01'),[view,setView]=useState('split'),[history,setHistory]=useState<Wall[][]>([]),[reset,setReset]=useState(0),[panels,setPanels]=useState(true),[message,setMessage]=useState('Selecione uma parede para editar.');
useWallTool(initial.map(w=>w.id),setSelected);
const wall=walls.find(w=>w.id===selected)!;
function change(field:'height'|'thickness',value:number){if(!Number.isFinite(value)||value<(field==='height'?.5:.05)||value>(field==='height'?6:.6)){setMessage('Valor fora do intervalo permitido.');return;}setHistory(h=>[...h,walls]);setWalls(ws=>ws.map(w=>w.id===selected?{...w,[field]:value}:w));setMessage(`${wall.name} atualizada nas duas vistas.`);}
return <main className="editor"><header className="titlebar"><strong><span className="brandmark">B</span> BRABIM</strong><span>Estudo 01 · Ambiente de exemplo</span><a className="prototype" href={sitePath("/ensaios/")}>ENSAIOS IFC →</a></header><div className="ribbon"><div className="ribbon-label">Arquitetura <span>/ Edição de paredes</span></div><div className="tools"><button className="tool active" onClick={()=>setMessage('Clique em uma parede na planta ou no 3D.')}><MousePointer2/>Selecionar</button><div className="toolgroup"><button className="tool" disabled={!history.length} onClick={()=>{setWalls(history[history.length-1]);setHistory(history.slice(0,-1));setMessage('Última alteração desfeita.');}}><Undo2/>Desfazer</button><button className="tool" onClick={()=>setReset(r=>r+1)}><RotateCcw/>Enquadrar</button></div><button className="tool" onClick={()=>setPanels(!panels)}><PanelLeft/>Painéis</button><div className="ribbon-note"><Layers size={19}/><div>Térreo <small>Elevação 0,00 m</small></div></div></div></div><div className={`workspace ${panels?'':'without-panel'}`}>
{panels&&<aside className="properties"><h2>Propriedades <span>{wall.id}</span></h2><div className="selected-card"><Layers/><div><strong>{wall.name}</strong><small>Parede básica · exemplo</small></div></div><section><h3>DIMENSÕES</h3><label htmlFor="height">Altura <span>m</span></label><input id="height" key={`${selected}-h-${wall.height}`} type="number" min="0.5" max="6" step="0.1" defaultValue={wall.height} onBlur={e=>{const v=Number(e.target.value);if(v!==wall.height)change('height',v);e.target.value=String(Number.isFinite(v)&&v>=.5&&v<=6?v:wall.height);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><label htmlFor="thickness">Espessura <span>m</span></label><input id="thickness" key={`${selected}-t-${wall.thickness}`} type="number" min="0.05" max="0.6" step="0.01" defaultValue={wall.thickness} onBlur={e=>{const v=Number(e.target.value);if(v!==wall.thickness)change('thickness',v);e.target.value=String(Number.isFinite(v)&&v>=.05&&v<=.6?v:wall.thickness);}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><dl><dt>Comprimento no eixo</dt><dd>{wall.length.toFixed(2)} m</dd><dt>Área bruta de face</dt><dd>{(wall.length*wall.height).toFixed(2)} m²</dd></dl><p className="hint">Enter ou sair do campo para aplicar.</p></section><section className="navigator"><h3>NAVEGADOR DO PROJETO</h3><p>⌄ Estudo 01</p><p className="level">⌄ Térreo · 5 paredes</p>{walls.map(w=><button key={w.id} className={w.id===selected?'selected':''} onClick={()=>setSelected(w.id)}><Layers size={14}/><span>{w.name}</span><small>{w.id}</small></button>)}</section><div className="panel-foot">Modelo ilustrativo, sem validação técnica.</div></aside>}
<div className="drawing"><div className="viewbar"><Tabs value={view} onValueChange={v=>setView(String(v))}><TabsList><TabsTrigger value="plan">Planta</TabsTrigger><TabsTrigger value="3d">3D</TabsTrigger><TabsTrigger value="split">Lado a lado</TabsTrigger></TabsList></Tabs><span className="viewmeta">Térreo / {wall.id}</span></div><div className={`views ${view==='split'?'split':''}`}>
{view!=='3d'&&<section className="view plan"><div className="view-title"><Layers size={16}/> Planta · Térreo <span>Metros</span></div><svg viewBox="-6 -4.5 12 9" aria-label="Planta com cinco paredes selecionáveis" className="plan-svg"><defs><pattern id="grid" width=".5" height=".5" patternUnits="userSpaceOnUse"><path d="M .5 0 L 0 0 0 .5" fill="none" stroke="#e7ecef" strokeWidth=".008"/></pattern></defs><rect x="-6" y="-4.5" width="12" height="9" fill="url(#grid)"/><rect x="-4" y="-2.5" width="8" height="5" fill="#f6f7f8"/><text x="-1.5" y="0" textAnchor="middle" fontSize=".22" fill="#78848e">AMBIENTE 01</text><text x="2.5" y="0" textAnchor="middle" fontSize=".22" fill="#78848e">AMBIENTE 02</text>{walls.map(w=><g key={w.id} transform={`translate(${w.x} ${w.z}) rotate(${w.angle*180/Math.PI})`}><rect role="button" tabIndex={0} aria-label={`Selecionar ${w.name}`} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(w.id);}}} onClick={()=>setSelected(w.id)} x={-w.length/2} y={-w.thickness/2} width={w.length} height={w.thickness} fill={selected===w.id?'#147db3':'#67727a'} stroke={selected===w.id?'#005b92':'#303b44'} strokeWidth=".025" className="wall"/></g>)}<g stroke="#8a99a3" strokeWidth=".015"><path d="M-4 -3 L4 -3 M-4 -3.2 L-4 -2.8 M4 -3.2 L4 -2.8 M-4.6 -2.5 L-4.6 2.5 M-4.8 -2.5 L-4.4 -2.5 M-4.8 2.5 L-4.4 2.5"/></g><g fill="#596a76" fontSize=".2"><text x="0" y="-3.12" textAnchor="middle">8,00 m · eixos</text><text x="-4.8" y="0" transform="rotate(-90 -4.8 0)" textAnchor="middle">5,00 m · eixos</text></g></svg><div className="view-caption"><MousePointer2 size={14}/> Clique em uma parede para selecionar</div></section>}
{view!=='plan'&&<section className="view three"><div className="view-title"><Box size={16}/> Perspectiva 3D <span>Modelo</span></div><Viewport walls={walls} selected={selected} onSelect={setSelected} reset={reset}/><div className="view-caption"><Move size={14}/> Arraste para orbitar · roda para aproximar</div></section>}</div></div></div><footer><span className="status-dot"/><span role="status">{message}</span><span className="footer-right">Alterações nesta sessão · unidades em metros</span></footer></main>;
}




export {default} from './room-editor';

