'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import type {Wall} from './page';
export type IfcMesh={id:string;guid:string;vertices:number[][];faces:number[][];height:number};
export default function Viewport({walls,selected,onSelect,reset,meshes}:{walls:Wall[];selected:string;onSelect:(id:string)=>void;reset:number;meshes?:IfcMesh[]}){
const host=useRef<HTMLDivElement>(null),data=useRef({walls,selected,onSelect,meshes}),update=useRef<()=>void>(()=>{}),home=useRef<()=>void>(()=>{});const [error,setError]=useState(false);data.current={walls,selected,onSelect,meshes};
useEffect(()=>{const el=host.current!;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch{setError(true);return;}renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(renderer.domElement);const scene=new THREE.Scene();scene.background=new THREE.Color('#eef2f5');const camera=new THREE.PerspectiveCamera(40,1,.1,100);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxDistance=35;controls.minDistance=5;controls.maxPolarAngle=Math.PI/2-.03;home.current=()=>{camera.position.set(11,10,13);controls.target.set(0,1,0);controls.update();};home.current();scene.add(new THREE.HemisphereLight(0xffffff,0x718393,2.5));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(5,10,4);scene.add(light);const grid=new THREE.GridHelper(24,24,0xc4d1da,0xdce3e9);grid.position.y=-.12;scene.add(grid);const floor=new THREE.Mesh(new THREE.BoxGeometry(8,.12,5),new THREE.MeshStandardMaterial({color:0xe0e4e5,roughness:1}));floor.position.y=-.07;scene.add(floor);const group=new THREE.Group();scene.add(group);
function clear(){group.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.LineSegments){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose());}});group.clear();}
update.current=()=>{clear();(data.current.meshes??data.current.walls).forEach(w=>{const imported='vertices' in w;const geometry=imported?new THREE.BufferGeometry():new THREE.BoxGeometry(w.length,w.height,w.thickness);if(imported){geometry.setAttribute('position',new THREE.Float32BufferAttribute(w.vertices.flatMap(([x,y,z])=>[x,z,-y]),3));geometry.setIndex(w.faces.flat());geometry.computeVertexNormals();}const mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:w.id===data.current.selected?0x258fc6:0xe6e5df,roughness:.8}));if(!imported){mesh.position.set(w.x,w.height/2,w.z);mesh.rotation.y=-w.angle;}mesh.userData.id=w.id;const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geometry),new THREE.LineBasicMaterial({color:w.id===data.current.selected?0x075781:0x78838b}));mesh.add(edges);group.add(mesh);});};update.current();const resize=new ResizeObserver(()=>{const width=el.clientWidth,height=el.clientHeight;if(!width||!height)return;camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(width,height,false);});resize.observe(el);const ray=new THREE.Raycaster();let start=[0,0];const down=(e:PointerEvent)=>{start=[e.clientX,e.clientY];};const up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-start[0],e.clientY-start[1])>5)return;const r=el.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(group.children,false)[0];if(hit)data.current.onSelect(hit.object.userData.id);};el.addEventListener('pointerdown',down);el.addEventListener('pointerup',up);renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});return()=>{renderer.setAnimationLoop(null);resize.disconnect();controls.dispose();clear();floor.geometry.dispose();(floor.material as THREE.Material).dispose();grid.geometry.dispose();(grid.material as THREE.Material).dispose();renderer.dispose();el.removeEventListener('pointerdown',down);el.removeEventListener('pointerup',up);el.replaceChildren();};},[]);
useEffect(()=>update.current(),[walls,selected,meshes]);useEffect(()=>home.current(),[reset]);return <div className="canvas-host" ref={host}>{error&&<p>O 3D precisa de WebGL. Você pode continuar na vista Planta.</p>}</div>;
}


