'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import type {Wall} from './page';
export type IfcMesh={id:string;guid:string;vertices:number[][];faces:number[][];height:number;material?:string};
// Stable, saturated color per material name so a layer keeps the same
// tint across recomputes and matches between the 3D view and the plan
// (hash the name instead of assigning by order).
export function materialColor(name:string){let h=0;for(let i=0;i<name.length;i++)h=(h*31+name.charCodeAt(i))>>>0;return '#'+new THREE.Color().setHSL((h%360)/360,.55,.62).getHexString();}
export default function Viewport({walls,selected,onSelect,onPick,reset,meshes,hideFloor=false,wireframe=false,sectionCut=false}:{walls:Wall[];selected:string;onSelect:(id:string)=>void;onPick?:(point:[number,number,number])=>void;reset:number;meshes?:IfcMesh[];hideFloor?:boolean;wireframe?:boolean;sectionCut?:boolean}){
const host=useRef<HTMLDivElement>(null),data=useRef({walls,selected,onSelect,onPick,meshes,wireframe,sectionCut}),update=useRef<()=>void>(()=>{}),home=useRef<()=>void>(()=>{});const [error,setError]=useState(false);data.current={walls,selected,onSelect,onPick,meshes,wireframe,sectionCut};
useEffect(()=>{const el=host.current!;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch{setError(true);return;}renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.localClippingEnabled=true;el.appendChild(renderer.domElement);const scene=new THREE.Scene();scene.background=new THREE.Color('#eef2f5');const camera=new THREE.PerspectiveCamera(40,1,.1,100);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxDistance=300;controls.minDistance=5;controls.maxPolarAngle=Math.PI/2-.03;home.current=()=>{const vertices=data.current.meshes?.flatMap(m=>m.vertices);if(vertices?.length){const bounds=new THREE.Box3().setFromPoints(vertices.map(([x,y,z])=>new THREE.Vector3(x,z,-y)));const center=bounds.getCenter(new THREE.Vector3()),radius=bounds.getSize(new THREE.Vector3()).length()/2;const fov=Math.min(camera.fov*Math.PI/180,2*Math.atan(Math.tan(camera.fov*Math.PI/360)*camera.aspect));const distance=radius/Math.sin(fov/2)*1.15;camera.far=Math.max(100,distance*4);camera.updateProjectionMatrix();camera.position.copy(center).add(new THREE.Vector3(1,.9,1.2).normalize().multiplyScalar(distance));controls.target.copy(center);controls.maxDistance=Math.max(35,distance*3);}else{camera.position.set(11,10,13);controls.target.set(0,1,0);}controls.update();};home.current();scene.add(new THREE.HemisphereLight(0xffffff,0x718393,2.5));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(5,10,4);scene.add(light);const grid=new THREE.GridHelper(24,24,0xc4d1da,0xdce3e9);grid.position.y=-.12;scene.add(grid);const floor=new THREE.Mesh(new THREE.BoxGeometry(8,.12,5),new THREE.MeshStandardMaterial({color:0xe0e4e5,roughness:1}));floor.position.y=-.07;if(!hideFloor)scene.add(floor);const group=new THREE.Group();scene.add(group);
// Section cut: clip away everything with Three.js Z>0 (app depth<0, the
// "near half" of the model) so you can look straight into a cross-section
// instead of guessing through solid geometry from the outside.
const clipPlane=new THREE.Plane(new THREE.Vector3(0,0,-1),0);
function clear(){group.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.LineSegments){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose());}});group.clear();}
update.current=()=>{clear();const clipPlanes=data.current.sectionCut?[clipPlane]:[];(data.current.meshes??data.current.walls).forEach(w=>{const imported='vertices' in w;const geometry=imported?new THREE.BufferGeometry():new THREE.BoxGeometry(w.length,w.height,w.thickness);if(imported){geometry.setAttribute('position',new THREE.Float32BufferAttribute(w.vertices.flatMap(([x,y,z])=>[x,z,-y]),3));geometry.setIndex(w.faces.flat());geometry.computeVertexNormals();}const layerColor=imported&&(w as IfcMesh).material?materialColor((w as IfcMesh).material!):undefined;const mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:w.id===data.current.selected?0x258fc6:layerColor??0xe6e5df,roughness:.8,wireframe:data.current.wireframe,clippingPlanes:clipPlanes,side:data.current.sectionCut?THREE.DoubleSide:THREE.FrontSide}));if(!imported){mesh.position.set(w.x,w.height/2,w.z);mesh.rotation.y=-w.angle;}mesh.userData.id=w.id;const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geometry),new THREE.LineBasicMaterial({color:w.id===data.current.selected?0x075781:0x78838b,clippingPlanes:clipPlanes}));mesh.add(edges);group.add(mesh);});};update.current();let firstResize=true;const resize=new ResizeObserver(()=>{const width=el.clientWidth,height=el.clientHeight;if(!width||!height)return;camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(width,height,false);if(firstResize){home.current();firstResize=false;}});resize.observe(el);const ray=new THREE.Raycaster();let start=[0,0];const down=(e:PointerEvent)=>{start=[e.clientX,e.clientY];};const up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-start[0],e.clientY-start[1])>5)return;const r=el.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(group.children,false)[0];if(hit){data.current.onSelect(hit.object.userData.id);data.current.onPick?.([hit.point.x,-hit.point.z,hit.point.y]);}};el.addEventListener('pointerdown',down);el.addEventListener('pointerup',up);renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});return()=>{renderer.setAnimationLoop(null);resize.disconnect();controls.dispose();clear();floor.geometry.dispose();(floor.material as THREE.Material).dispose();grid.geometry.dispose();(grid.material as THREE.Material).dispose();renderer.dispose();el.removeEventListener('pointerdown',down);el.removeEventListener('pointerup',up);el.replaceChildren();};},[]);
useEffect(()=>update.current(),[walls,selected,meshes,wireframe,sectionCut]);useEffect(()=>home.current(),[reset]);return <div className="canvas-host" ref={host}>{error&&<p>O 3D precisa de WebGL. Você pode continuar na vista Planta.</p>}</div>;
}





